{
 "title": "Dashboard",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"text-align: center; font-size: 48px\">Anomaly detection</p>"
   }
  },
  {
   "title": "System metrics",
   "type": "timeseries",
   "description": "CPU usage %",
   "gridPos": { "h": 20, "w": 15, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "queryText": "metrics" }
   ]
  },
  {
   "title": "CPU Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, expected, actual, diff FROM alerts.cpu WHERE time < (now() - interval '1' second) ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "CPU Temperature Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, expected, actual, diff FROM alerts.cpu_temp WHERE time < (now() - interval '1' second) ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "RAM Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, expected, actual, diff FROM alerts.ram WHERE time < (now() - interval '1' second) ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "Swap Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, expected, actual, diff FROM alerts.swap WHERE time < (now() - interval '1' second) ORDER BY time DESC;"
    }
   ]
  },
  {
   "title": "Disk Alerts",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT time, expected, actual, diff FROM alerts.disk WHERE time < (now() - interval '1' second) ORDER BY time DESC;"
    }
   ]
  }
 ]
}